### ISSUE TITLE
SVG watermark image are not appearing in pdf

### ISSUE THREAD

**Issue by bborad** [selectpdf/html-to-pdf-api#1]
Hi 

there seem to be some parameters missing in the document on selectpdf website.  I am trying add svg image as watermark in pdf but api is not printing it in pdf. However same html code works if I test it from selectpdf website. 

code is available here https://stackoverflow.com/questions/55860602/selectpdf-not-printing-background-svg-image

**Comment by selectpdf** [comment]
If you use base64 encoded images with the API, set the parameter skip_decoding to True.

**Comment by kkrzaczkowski** [comment]
How to set the parameter "skip_decoding" for True ? 
I checked documentation and "HtmlToPdfOptions" class and did not find this property.

It is important for my client and has an impact on the decision whether to buy this library.

**Comment by selectpdf** [comment]
This github repository is related to our HTML TO PDF Online API product. It's not about the .NET library.

**Comment by tihomir-kit** [comment]
With all due respect, but since you already gave the man a pointer that skip_decoding should be set to true, you might have as well given him that one extra bit of information which would have made the time spent on writing the final reply useful. Googling doesn't yield anything meaningful.
